#! /bin/sh

sh() {
  /bin/sh -c "set -x; $*"
}

sh autopoint # for GNU gettext
sh libtoolize --copy --force --automake
sh aclocal
sh autoheader
sh autoconf
sh automake --foreign --include-deps --add-missing --copy

echo
echo You are now ready to run ./configure
echo enjoy!
