.TH xftlsfonts 1 "August 2002" "xftlsfonts" "v1.0"
.SH NAME
xftlsfonts - display Xft fonts found
.SH SYNOPSIS
\fBxftlsfonts\fR [options]
.SH DESCRIPTION
\fBxftlsfonts\fR is intended to display the Xft fonts that the X Window System
currently supports.
.SH OPTIONS
.TP
\fB\-style\fR
Show possible styles for each of the fonts.
.TP
\fB\-slant\fR
Show the slant for each of the fonts.
.TP
\fB\-weight\fR
Show the weight for each of the fonts.
.TP
\fB\-file\fR
Show which file contains each of the fonts.
.TP
.SH CONFIGURATION
\fIxftlsfonts\fR will work without any arguments, assuming a default behaviour.
.SH AUTHOR
The author of xftlsfonts is Ben Jansens <\fIben@orodu.net\fB>.
.SH SEE ALSO
\fIopenbox\fR(1)
