Document: openbox
Title: Debian openbox Manual
Author: <insert document author here>
Abstract: This manual describes what openbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openbox/openbox.sgml.gz

Format: postscript
Files: /usr/share/doc/openbox/openbox.ps.gz

Format: text
Files: /usr/share/doc/openbox/openbox.text.gz

Format: HTML
Index: /usr/share/doc/openbox/html/index.html
Files: /usr/share/doc/openbox/html/*.html

  
